import { z } from "zod";

export const ProfileSchema = z.object({
  nome: z.string().optional().default("Paciente MedV2"),
  idade: z.coerce.number().optional().default(0),
  sexo: z.string().optional().default(""),
  altura: z.coerce.number().optional().default(0),
  peso: z.coerce.number().optional().default(0),
  imc: z.coerce.number().optional().default(0),
  massaMagra: z.coerce.number().optional().default(0),
  inbodyScore: z.coerce.number().optional().nullable().default(null),
  cardioSistolica: z.coerce.number().optional().default(0),
  cardioDiastolica: z.coerce.number().optional().default(0),
  cardioFcRepouso: z.coerce.number().optional().default(0),
  objetivos: z.string().optional().default(""),
  historicoFamiliar: z.string().optional().default(""),
  observacoes: z.string().optional().default(""),
  condicoesMedicas: z.string().optional().default(""),
  medicamentos: z.string().optional().default(""),
  alergias: z.string().optional().default(""),
  cirurgias: z.string().optional().default(""),
  
  sonoHoras: z.coerce.number().optional().default(0),
  sonoQualidade: z.coerce.number().optional().default(0),
  sonoTempoCama: z.coerce.number().optional().default(0),
  sonoRegularidade: z.string().optional().default(""),
  sonoProblemas: z.string().optional().default(""),
  aguaDia: z.coerce.number().optional().default(0),
  nivelEstresse: z.coerce.number().optional().default(0),
  tabagismo: z.string().optional().default(""),
  dietaAtual: z.string().optional().default(""),
  gestaoEstresse: z.string().optional().default(""),
  suplementacaoAtual: z.string().optional().default(""),
  cronoExposicaoSolar: z.string().optional().default(""),
  cronoUltimaRefeicao: z.string().optional().default(""),
  cronoLuzArtInicio: z.string().optional().default(""),
  cronoLuzArtFim: z.string().optional().default(""),
  cronoObsLuz: z.string().optional().default(""),

  perfForcaPreensao: z.coerce.number().optional().default(0),
  perfSentarLevantar: z.coerce.number().optional().default(0),
  perfVo2Max: z.coerce.number().optional().default(0),
  perfToleranciaCo2: z.coerce.number().optional().default(0),
  perfAtividadeFisica: z.string().optional().default(""),
  limitacoesFisicas: z.string().optional().default(""),

  // Diet & Digestion Anamnesis
  dietType: z.string().optional().default(""),
  eatingPattern: z.string().optional().default(""),
  proteinIntake: z.string().optional().default(""),
  fluidIntake: z.string().optional().default(""),
  dietaryRestrictions: z.string().optional().default(""),
  alcoholConsumption: z.string().optional().default(""),
  caffeineIntake: z.string().optional().default(""),
  latestCaffeineTime: z.string().optional().default(""),
  recentDietChanges: z.string().optional().default(""),
  typicalMeals: z.string().optional().default(""),
  bowelFrequency: z.string().optional().default(""),
  stoolConsistency: z.string().optional().default(""),
  bloating: z.string().optional().default(""),
  gas: z.string().optional().default(""),
  acidReflux: z.string().optional().default(""),
  burping: z.string().optional().default(""),
  nausea: z.string().optional().default(""),
  appetite: z.string().optional().default(""),
  abdominalPain: z.string().optional().default(""),
  foodSensitivities: z.string().optional().default(""),
  dietaryNotes: z.string().optional().default(""),

  // Exercise Anamnesis
  exerciseFrequency: z.string().optional().default(""),
  exerciseTypes: z.string().optional().default(""),
  exerciseIntensity: z.string().optional().default(""),
  typicalSessionDuration: z.string().optional().default(""),
  dailyMovement: z.string().optional().default(""),
  muscleContext: z.string().optional().default(""),
  limitationsAndRecovery: z.string().optional().default(""),
  exerciseNotes: z.string().optional().default("")
});

export type Profile = z.infer<typeof ProfileSchema>;
